export const DATEPICKER_CALENDAR_SIZES = {
  MIN_WIDTH: '10.5rem',
  MONTH_PICKER_WIDTH: '10rem',
  BORDER_RADIUS: '0.625rem',
  BORDER_WIDTH: '0.125rem',
  DAY_SIZE: '2rem',
  DAY_MARGIN: '0.166rem',
  MONTH_MARGIN: '0.4rem',
  HEADER_PADDING_TOP: '0.5rem',
  HEADER_PADDING_SIDE: '0.25rem',
  NAVIGATION_SIZE: '2rem',
  NAVIGATION_TOP: '0.625rem',
  NAVIGATION_SIDE: '0.25rem',
  ICON_SIZE: '0.5rem',
  ICON_TOP: '0.375rem',
  MONTH_TEXT_WIDTH: '2.75rem',
  MONTH_TEXT_HEIGHT: '1.75rem',
  MONTH_GAP: '0.25rem',
  MONTH_PADDING: '0.5rem',
} as const;

export const DATEPICKER_CALENDAR_Z_INDEX = '1000';
