import React from 'react';
import { Locale } from 'date-fns';

export type DatePickerSize = 'sm' | 'md' | 'lg';

export interface DatePickerProps {
  size?: DatePickerSize;
  onClear?: () => void;
  calendarIcon?: React.ReactNode;
  clearIcon?: React.ReactNode;
  fullWidth?: boolean;
  baseClassName?: string;
  wrapperClassName?: string;
  disableDefaultStyles?: boolean;
  locale?: Locale;
  selected?: Date | null;
  onChange?: (date: Date | null, event?: React.SyntheticEvent<unknown> | undefined) => void;
  placeholderText?: string;
  dateFormat?: string;
  disabled?: boolean;
  readOnly?: boolean;
  minDate?: Date | null;
  maxDate?: Date | null;
  filterDate?: (date: Date) => boolean;
  includeDates?: Date[];
  excludeDates?: Date[];
  highlightDates?: Date[];
  showMonthDropdown?: boolean;
  showYearDropdown?: boolean;
  showMonthYearPicker?: boolean;
  dropdownMode?: 'scroll' | 'select';
  showTimeSelect?: boolean;
  timeFormat?: string;
  timeIntervals?: number;
  timeCaption?: string;
  showTimeSelectOnly?: boolean;
  dateFormatCalendar?: string;
  monthsShown?: number;
  inline?: boolean;
  fixedHeight?: boolean;
  selectsRange?: boolean;
  startDate?: Date | null;
  endDate?: Date | null;
  selectsStart?: boolean;
  selectsEnd?: boolean;
  isClearable?: boolean;
  clearButtonClassName?: string;
  shouldCloseOnSelect?: boolean;
  showPopperArrow?: boolean;
  autoComplete?: string;
  className?: string;
  bg?: string;
  textColor?: string;
  borderColor?: string;
  focusBorderColor?: string;
  focusShadow?: string;
  iconColor?: string;
  iconHoverColor?: string;
  placeholderColor?: string;
  calendarBg?: string;
  calendarHeaderBg?: string;
  calendarSelectedBg?: string;
  calendarHoverBg?: string;
}
